In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('wildfire_train.csv')

In [8]:
X = dataset[['avg_dry_bulb_temperature', 'avg_dew_point','avg_relative_humidity','avg_rain_mm','avg_snow_cm','avg_hail_mm','avg_precipitation_mm','avg_wind_speed_kmh','avg_wind_gust_kmh','avg_wind_azimuth','avg_ffmc','avg_dmc','avg_dc','avg_isi','avg_bui','avg_fwi','avg_edr']]
Y = dataset[['is_fire']]

In [41]:
wildfire_data = wildfire_data_raw[['avg_dry_bulb_temperature', 'avg_dew_point','avg_relative_humidity','avg_rain_mm','avg_snow_cm','avg_hail_mm','avg_precipitation_mm','avg_wind_speed_kmh','avg_wind_gust_kmh','avg_wind_azimuth','avg_ffmc','avg_dmc','avg_dc','avg_isi','avg_bui','avg_fwi','avg_edr','is_fire']]

In [44]:
wildfire_data.dropna()

,avg_dry_bulb_temperature,avg_dew_point,avg_relative_humidity,avg_rain_mm,avg_snow_cm,avg_hail_mm,avg_precipitation_mm,avg_wind_speed_kmh,avg_wind_gust_kmh,avg_wind_azimuth,avg_ffmc,avg_dmc,avg_dc,avg_isi,avg_bui,avg_fwi,avg_edr,is_fire
52,9.444444,1.055556,57.166667,0.037222,0.0,0.0,0.037222,14.222222,45.000000,280.000000,76.791667,6.650000,60.100000,2.100000,9.608333,1.933333,0.135833,0
53,13.888889,3.777778,53.944444,1.151667,0.0,0.0,1.151667,16.388889,45.000000,130.000000,76.943750,16.762500,85.412500,3.981250,21.262500,5.962500,0.955625,0
61,22.166667,9.111111,44.388889,0.000000,0.0,0.0,0.000000,9.500000,42.000000,162.500000,87.576471,28.152941,288.517647,5.558824,44.435294,12.758824,2.838824,0
63,13.600000,-3.600000,31.133333,0.001333,0.0,0.0,0.001333,7.066667,26.500000,111.000000,86.571429,33.928571,90.000000,4.071429,35.500000,9.071429,1.569286,0
66,12.294118,2.000000,50.058824,0.005882,0.0,0.0,0.005882,15.647059,37.666667,285.882353,80.250000,18.750000,108.875000,2.906250,25.875000,5.687500,0.727500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106813,7.360000,3.720000,77.720000,1.998000,0.0,0.0,1.998000,8.000000,8.000000,144.000000,66.480000,11.800000,299.200000,1.200000,20.880000,2.200000,0.228000,0
106814,11.880000,5.160000,63.082000,0.152000,0.0,0.0,0.152000,8.400000,32.000000,216.000000,83.400000,12.480000,306.800000,2.880000,22.320000,4.920000,0.558000,0
106829,10.225000,-2.512500,41.001250,0.000000,0.0,0.0,0.000000,12.750000,39.000000,157.500000,88.150000,14.000000,226.950000,6.600000,24.100000,11.050000,2.035000,0
106906,-9.150000,-11.000000,81.500000,0.000000,0.0,0.0,0.000000,2.000000,5.500000,22.500000,83.950000,6.000000,30.600000,2.050000,8.100000,1.350000,0.050000,0
107225,11.175000,-4.750000,31.500000,0.000000,0.0,0.0,0.000000,14.750000,30.000000,191.250000,89.250000,10.350000,98.800000,10.650000,14.000000,11.900000,2.225000,0

In [45]:
X = wildfire_data_raw[['avg_dry_bulb_temperature', 'avg_dew_point','avg_relative_humidity','avg_rain_mm','avg_snow_cm','avg_hail_mm','avg_precipitation_mm','avg_wind_speed_kmh','avg_wind_gust_kmh','avg_wind_azimuth','avg_ffmc','avg_dmc','avg_dc','avg_isi','avg_bui','avg_fwi','avg_edr']]
Y = wildfire_data_raw['is_fire']

In [46]:
X

,avg_dry_bulb_temperature,avg_dew_point,avg_relative_humidity,avg_rain_mm,avg_snow_cm,avg_hail_mm,avg_precipitation_mm,avg_wind_speed_kmh,avg_wind_gust_kmh,avg_wind_azimuth,avg_ffmc,avg_dmc,avg_dc,avg_isi,avg_bui,avg_fwi,avg_edr
0,20.294118,1.058824,28.058824,0.000000,0.0,0.0,0.000000,18.529412,NaN,230.294118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19.588235,-1.882353,24.470588,0.047059,0.0,0.0,0.047059,7.941176,NaN,203.823529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.882353,1.705882,97.705882,12.276471,0.0,0.0,12.276471,15.941176,NaN,113.823529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.411765,1.058824,80.882353,2.055294,0.0,0.0,2.055294,11.647059,NaN,129.705882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16.647059,5.235294,48.588235,7.230588,0.0,0.0,7.230588,17.705882,NaN,108.529412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107330,5.300000,-6.000000,41.000000,0.000000,0.0,0.0,0.000000,6.000000,NaN,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107331,4.600000,-9.000000,35.000000,0.000000,0.0,0.0,0.000000,6.000000,22.0,135.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107332,1.400000,-11.000000,37.000000,0.000000,0.0,0.0,0.000000,4.000000,NaN,270.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107333,4.900000,-7.000000,41.000000,0.000000,0.0,0.0,0.000000,5.000000,NaN,180.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107334,1.500000,-6.500000,52.000000,0.000000,0.0,0.0,0.000000,17.500000,36.0,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
Y

0         0
1         0
2         0
3         0
4         0
         ..
107330    0
107331    0
107332    0
107333    0
107334    0
Name: is_fire, Length: 107335, dtype: int64

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.25,random_state=0)

In [49]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [50]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [27]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [29]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

In [30]:
cm

array([[8192,    0],
       [   0, 1832]], dtype=int64)

In [32]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

KNeighborsClassifier()

In [33]:
# Predicting the Test set results
y_pred_knn = classifier.predict(X_test)

In [35]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(Y_test, y_pred_knn)

In [36]:
cm_knn

array([[8191,    1],
       [  18, 1814]], dtype=int64)